name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install
        run: composer require squizlabs/php_codesniffer ~3.0

      - name: install
        run: composer require slevomat/coding-standard ~4.0

      - name: ls
        run: ls -la

      - name: Sniffer job
        run: |
          phpcs -p --standard=ruleset.xml --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 app/Http/Controllers/ tests
